Proyecto-B/errorPages/errorPages/urls.py
from django.contrib import admin
from django.urls import path, include
from app.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name='index'),
    path('error/', generar_error, name='error'),
    path('onepage/',onepage, name='onepage'),
    path('prueba/', prueba_front,name='prueba'),
    path('search/', search_view, name='search'),
    path('error_logs/', error_logs, name='error_logs'),
    path('api/error_logs/', get_error_logs, name='get_error_logs'),
    path('users/', include('users.urls')),
    path('productos/', include('productos.urls')),
    path('categoria/', include('categorías.urls')),
    path('alumnos/', include('alumnos.urls')),
]

Proyecto-B/errorPages/users/urls.py
from django.urls import path,include
from .views import *
from rest_framework.routers import SimpleRouter
from rest_framework_simplejwt.views import TokenRefreshView

router = SimpleRouter()
router.register(r'api', UserViewSets) #get, post, put, delete

urlpatterns = [
   path('', include(router.urls)),
   #Este es el path para iniciar sesion <- requiere email y password
   path('token/', CustomTokenObtainPairView.as_view(), name='token'),
   path('token/refresh/', TokenRefreshView.as_view(), name='refresh'),
   path('form/', CustomUserFormAPI.as_view(), name="form"),
   path("send-reset-email/", send_reset_email, name="send_reset_email"),
   path("reset-password/", reset_password, name="reset_password"),
]

Proyecto-B/errorPages/users/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin 
from django.db import models
from django.utils.timezone import now

class CustomUserManager(BaseUserManager):
    def create_user(self, email, password, name, surname, age, tel, control_number, address, **extra_fields):
       if not email:
           raise ValueError('El correo electrónico es obligatorio')
       email = self.normalize_email(email)
       user = self.model(email=email, **extra_fields)
       user.set_password(password)
       user.name = name
       user.surname = surname
       user.age = age
       user.tel = tel
       user.control_number = control_number
       user.address = address
       user.save(using=self._db)
       return user
   
    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, password, **extra_fields)
    
class CustomUser(AbstractBaseUser, PermissionsMixin):
   email = models.EmailField(unique=True)
   token = models.CharField(max_length=255, blank=True, null=True)
   name = models.CharField(max_length=100)
   surname = models.CharField(max_length=100)
   control_number = models.CharField(max_length=20, unique=True)
   age = models.PositiveIntegerField()
   tel = models.CharField(max_length=15)
   address = models.CharField(max_length=255, blank=True, null=True)  # Nuevo campo
   join_date = models.DateTimeField(default=now)
   is_active = models.BooleanField(default=True)
   is_staff = models.BooleanField(default=False)
   
   objects = CustomUserManager()
   
   USERNAME_FIELD = 'email'
   REQUIRED_FIELDS = ['name', 'surname', 'control_number', 'age', 'tel', 'gener']

   def __str__(self):
       return self.email

Proyecto-B/errorPages/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
import re
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    password1 = forms.CharField(
        label="Contraseña",
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "required": True,
                "placeholder": "Contraseña",
            }
        ),
    )

    password2 = forms.CharField(
        label="Confirmar contraseña",
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "required": True,
                "placeholder": "Confirmar contraseña",
            }
        ),
    )

    class Meta:
        model = CustomUser
        fields = [
            "email",
            "name",
            "surname",
            "control_number",
            "age",
            "tel",
            "address",
            "password1",
            "password2",
        ]

        widgets = {
            "email": forms.EmailInput(
                attrs={
                    "class": "form-control",
                    "required": True,
                    "placeholder": "Correo electrónico",
                    "title": "Correo electrónico de la UTEZ",
                }
            ),
            "name": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "required": True,
                    "placeholder": "Nombre:",
                    "title": "Nombre(s)",
                }
            ),
            "surname": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "required": True,
                    "placeholder": "Apellido:",
                    "title": "Apellido paterno y materno",
                }
            ),
            "control_number": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "required": True,
                    "placeholder": "Número de control:",
                    "title": "Número de control de 9 dígitos",
                }
            ),
            "age": forms.NumberInput(
                attrs={
                    "class": "form-control",
                    "required": True,
                    "placeholder": "Edad:",

                    "title": "Edad en años",
                }
            ),
            "tel": forms.NumberInput(
                attrs={
                    "class": "form-control",
                    "required": True,
                    "placeholder": "Teléfono:",
                    "title": "10 dígitos",
                }
            ),
            "address": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "required": True,
                    "placeholder": "Dirección:",
                    "title": "Dirección completa",
                }
            ),
        }

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if not re.match(r"^[a-zA-Z0-9._%+-]+@utez\.edu\.mx$", email):
            raise forms.ValidationError("El correo debe ser del dominio @utez.edu.mx")
        return email

    def clean_password1(self):
        password1 = self.cleaned_data.get("password1")
        if not re.match(
            r"^(?=.*\d)(?=.*[!#$%&?])(?=.*[A-Z])(?=.*[a-z]).{8,}$", password1
        ):
            raise forms.ValidationError(
                "La contraseña debe tener al menos 8 caracteres, una mayúscula, una minúscula, un número y un carácter especial (!, #, $, %, & o ?)."
            )
        return password1

    def clean_control_number(self):
        control_number = self.cleaned_data.get("control_number")
        if not re.match(r"^\d{5}[a-zA-Z]{2}\d{3}$", control_number):
            raise forms.ValidationError(
                "El número de control debe tener exactamente 10 caracteres con el formato correcto."
            )
        return control_number

    def clean_tel(self):
        tel = self.cleaned_data.get("tel")
        if not re.match(r"^\d{10}$", str(tel)):
            raise forms.ValidationError(
                "El teléfono debe contener exactamente 10 dígitos."
            )
        return tel

    def clean_age(self):
        age = self.cleaned_data.get("age")
        if age < 1 or age > 120:
            raise forms.ValidationError("La edad debe estar entre 1 y 120 años.")
        return age

    def clean_name(self):
        name = self.cleaned_data.get("name")
        if len(name) < 2 or len(name) > 100:
            raise forms.ValidationError(
                "El nombre debe tener entre 2 y 100 caracteres."
            )
        return name

    def clean_surname(self):
        surname = self.cleaned_data.get("surname")
        if len(surname) < 2 or len(surname) > 100:
            raise forms.ValidationError(
                "El apellido debe tener entre 2 y 100 caracteres."
            )
        return surname

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Las contraseñas no coinciden.")

        return cleaned_data


class CustomUserLoginForm(AuthenticationForm):
    username = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "class": "form-control",
                "required": True,
                "pattern": "^[a-zA-Z0-9]+@utez\.edu\.mx$",
                "placeholder": "Correo electrónico",
                "title": "Correo electrónico de la UTEZ",
            }
        )
    )

    password = forms.CharField(
        label="Contraseña",
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "required": True,
                "placeholder": "Contraseña",
                "pattern": "^(?=.*\d)(?=.*[!#$%&?])(?=.*[A-Z])(?=.*[a-z]).{8,}$",
                "title": "Debe contener al menos 8 caracteres, una mayúscula, una minúscula, un número y un carácter especial",
            }
        ),
    )

Proyecto-B/errorPages/users/views.py
from rest_framework.renderers import JSONRenderer
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated
from .models import CustomUser
from .forms import CustomUserCreationForm
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from .serializers import CustomUserSerializer, CustomTokenObtainPairSerializer
from rest_framework_simplejwt.authentication import JWTAuthentication
import secrets
from django.core.mail import send_mail
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.hashers import make_password

#Hacer las vistas del API_REST de usuarios 
class UserViewSets(viewsets.ModelViewSet):
    queryset = CustomUser.objects.all()
    serializer_class = CustomUserSerializer
    renderer_classes = [JSONRenderer]

    #Si quieres agregar la parte de seguridad pon estas 2 variables
    authentication_classes = [JWTAuthentication] #Si es un token
    permission_classes = [IsAuthenticated]  #Si tengo la sesión activa

    #Que métodos va a proteger
    def get_permissions(self):
        if self.request.method in ['POST','PUT','DELETE']:
            return [IsAuthenticated()]
        return []

from rest_framework_simplejwt.views import TokenObtainPairView
#Hacer una vista que me devuelva mi token
class CustomTokenObtainPairView(TokenObtainPairView):
    serializer_class = CustomTokenObtainPairSerializer
    

class CustomUserFormAPI(APIView):
    def get(self, request, *args, **kwargs):
        form = CustomUserCreationForm()
        fields = {}

        for field in form.fields:
            fields[field] = {
                'label': form[field].label,
                'input': form[field].field.widget.attrs,
                'type': form[field].field.widget.input_type,
            }

        return Response(fields)

    def post(self, request, *args, **kwargs):
        form = CustomUserCreationForm(request.data)

        if form.is_valid():
            user_data = form.cleaned_data
            User = get_user_model()
            user = User.objects.create_user(
                email=user_data['email'],
                password=user_data['password1'],
                name=user_data['name'],
                surname=user_data['surname'],
                control_number=user_data['control_number'],
                age=user_data['age'],
                tel=user_data['tel'],
                address=user_data['address'],
            )

            return Response({'message': 'Usuario creado con éxito'}, status=status.HTTP_201_CREATED)

        return Response(form.errors, status=status.HTTP_400_BAD_REQUEST)
    
@csrf_exempt
def send_reset_email(request):
    if request.method == "POST":
        #LLega del request de React información del email del usuario que quiere restablecer la contraseña
        email = request.POST.get("email")
        #Busquemos al usuario porque puede ser que no exista en el sistema
        user = CustomUser.objects.filter(email=email).first()
        if user:
            # Generar un token aleatorio de 20 caracteres
            token = secrets.token_urlsafe(20)

            # Las siguientes 2 lineas guarda el token en la BD
            user.token = token
            user.save()

            # Queremos que desde el correo electronica exista un link que incluya el token para que desde gmail (u otro) el usuario pueda regresar al sistema
            # y cambie su conraseña (debemos revisar que el token sea igual al que esta la BD para ello)
            # Construir el enlace de recuperación, en este caso lo dejamos en localhost pero deberia cambiar en producción
            reset_link = f"http://localhost:5173/reset-password/{token}"

            #Envio de correo
            send_mail(
                subject="🔐 Recuperación de contraseña",
                message=f"Hola, usa este enlace para restablecer tu contraseña: {reset_link}",  
                from_email="no-reply@errorpages.com",
                recipient_list=[email],
                fail_silently=False,
                html_message=f"""
                <html>
                <body style="font-family: Arial, sans-serif; color: #333;">
                    <h2 style="color: #0066cc;">Recuperación de contraseña</h2>
                    <p>Hola,</p>
                    <p>Has solicitado restablecer tu contraseña. Para continuar, haz clic en el siguiente botón:</p>
                    <p>
                        <a href="{reset_link}" 
                        style="display: inline-block; padding: 10px 20px; background-color: #0066cc; color: #ffffff; 
                                text-decoration: none; font-weight: bold; border-radius: 5px;">
                            Restablecer contraseña
                        </a>
                    </p>
                    <p>O copia y pega este enlace en tu navegador:</p>
                    <p><a href="{reset_link}" style="color: #0066cc;">{reset_link}</a></p>
                    <p>Si no solicitaste este cambio, ignora este mensaje.</p>
                    <p>Saludos,<br>El equipo de ErrorPages</p>
                </body>
                </html>
                """
            )
            #Regresamos mensaje de exito a React
            return JsonResponse({"message": "Correo de recuperación enviado."}, status=200)
        #Regresamos mensaje de error a React
        return JsonResponse({"error": "Usuario no encontrado"}, status=404)


#Vista que verificara que el token del usuario sea correcto y realiza el cambio de contraseña
@csrf_exempt
def reset_password(request):
    #Llega información desde el front con react
    if request.method == "POST":
        token = request.POST.get("token")
        new_password = request.POST.get("password")
        #Buscamos al usuario por token (ya que deberia ser unico y debe ser correcto, si no nos estan hackeando 0_0)
        user = CustomUser.objects.filter(token=token).first()

        if user:
            user.password = make_password(new_password)  # Encripta la nueva contraseña
            user.token = None  # Eliminar el token después de usarlo
            user.save()

            #Envio de correo
            send_mail(
                subject="🔐 Recuperación de contraseña",
                message=f"Tu contraseña fue cambiada con exito!",  # Texto plano (fallback)
                from_email="no-reply@errorpages.com",
                recipient_list=[user.email],
                fail_silently=False,
                html_message=f"""
                <html>
                <body style="font-family: Arial, sans-serif; color: #333;">
                    <h2 style="color: #0066cc;">¡Tu contraseña fue cambiada con exito!</h2>
                    <p>Hola,</p>
                    <p>Tu contraseña ha cambiado recientemente, haz clic en el siguiente botón para iniciar sesión:</p>
                    <p>
                        <a href="http://localhost:5173/login/" 
                        style="display: inline-block; padding: 10px 20px; background-color: #0066cc; color: #ffffff; 
                                text-decoration: none; font-weight: bold; border-radius: 5px;">
                            Iniciar sesión
                        </a>
                    </p>
                    <p>Si no solicitaste este cambio, Tu cuenta esta en peligro, ponte en contacto con admin@errorpages.com.</p>
                    <p>Saludos,<br>El equipo de ErrorPages</p>
                </body>
                </html>
                """
            )

            return JsonResponse({"message": "Contraseña restablecida exitosamente."})
        return JsonResponse({"error": "Token inválido"}, status=400)

Proyecto-B/errorPages/users/templates/home.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <h1>Bienvenido a la página principal</h1>
    <a href="{% url 'logout' %}">Cerrar sesión</a>
</body>
</html>

Proyecto-B/errorPages/users/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header text-center">
                        <h3>Iniciar Sesión</h3>
                    </div>
                    <div class="card-body">
                        <form method="post" onsubmit="return validateForm()">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="id_email" class="form-label">Nombre de Usuario</label>
                                {{ form.username }}
                            </div>
                            <div class="mb-3">
                                <label for="id_password" class="form-label">Contraseña</label>
                                {{ form.password }}
                            </div>
                            <button type="submit" class="btn btn-primary w-100">Iniciar sesión</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <script>
        function validateForm(){
            var password = document.getElementById('id_password').value;
            var regex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[$@$!%*?&]).{8,}$/;

            if(password.length < 8){
                Swal.fire({
                    title: 'Error',
                    text: 'La contraseña debe tener al menos 8 caracteres.',
                    icon: 'error',
                    confirmButtonText: 'Aceptar'
                });
                return false;
            }

            if (!regex.test(password)) {
                Swal.fire({
                    title: 'Error',
                    text: 'La contraseña debe incluir una mayúscula, un número y un símbolo (!, #, $, %, & o ?).',
                    icon: 'error',
                    confirmButtonText: 'Aceptar'
                });
                return false;
            }

            return true;
        }
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
    {% include 'mensaje.html' %}
</body>
</html>

Proyecto-B/errorPages/users/templates/register.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Register</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />

    <style>
        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }
  
        html,
        body {
          height: 100%;
        }
  
        body {
          display: flex;
          flex-direction: column;
          font-family: Arial, sans-serif;
          background-color: #f8f9fa;
          color: #333;
        }
  
        .container {
          flex: 1;
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
        }
  
        form {
          display: flex;
          flex-direction: column;
          justify-content: center;
          margin-top: 20px;
          width: 50%;
        }
  
        @media (max-width: 768px) {
          form {
            width: 100%;
          }
        }
  
        footer {
          text-align: center;
          padding: 10px 0;
          background-color: #f8f9fa;
        }
      </style>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">Home</a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'register' %}">Register</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <div class="container">
      <h2>Register</h2>
      <form method="POST" id="register-form">
        {% csrf_token %}

        <div class="mb-3">
          <label for="id_email" class="form-label">Correo Electrónico</label>
          {{ form.email }} {% if form.email.errors %}
          <div class="text-danger">{{ form.email.errors.0 }}</div>
          {% endif %}
        </div>

        <div class="mb-3">
          <label for="id_name" class="form-label">Nombre</label>
          {{ form.name }} {% if form.name.errors %}
          <div class="text-danger">{{ form.name.errors.0 }}</div>
          {% endif %}
        </div>

        <div class="mb-3">
          <label for="id_surname" class="form-label">Apellido</label>
          {{ form.surname }} {% if form.surname.errors %}
          <div class="text-danger">{{ form.surname.errors.0 }}</div>
          {% endif %}
        </div>

        <div class="mb-3">
          <label for="id_control_number" class="form-label"
            >Número de Control</label
          >
          {{ form.control_number }} {% if form.control_number.errors %}
          <div class="text-danger">{{ form.control_number.errors.0 }}</div>
          {% endif %}
        </div>

        <div class="mb-3">
          <label for="id_age" class="form-label">Edad</label>
          {{ form.age }} {% if form.age.errors %}
          <div class="text-danger">{{ form.age.errors.0 }}</div>
          {% endif %}
        </div>

        <div class="mb-3">
          <label for="id_tel" class="form-label">Teléfono</label>
          {{ form.tel }} {% if form.tel.errors %}
          <div class="text-danger">{{ form.tel.errors.0 }}</div>
          {% endif %}
        </div>

        <label for="id_password1" class="form-label">Contraseña</label>
        <div class="input-group mb-3">
          {{ form.password1 }}
          <button
            type="button"
            class="btn btn-outline-secondary toggle-password"
            data-target="#id_password1"
          >
            <img
              src="https://cdn-icons-png.flaticon.com/128/158/158746.png"
              class="password-icon"
              width="24"
            />
          </button>
        </div>
        {% if form.password1.errors %}
        <div class="text-danger">{{ form.password1.errors.0 }}</div>
        {% endif %}

        <label for="id_password2" class="form-label"
          >Confirmar Contraseña</label
        >
        <div class="input-group mb-3">
          {{ form.password2 }}
          <button
            type="button"
            class="btn btn-outline-secondary toggle-password"
            data-target="#id_password2"
          >
            <img
              src="https://cdn-icons-png.flaticon.com/128/158/158746.png"
              class="password-icon"
              width="24"
            />
          </button>
        </div>
        {% if form.password2.errors %}
        <div class="text-danger">{{ form.password2.errors.0 }}</div>
        {% endif %}

        <button type="submit" class="btn btn-success">Register</button>
      </form>
    </div>

    <footer>
      <p>© 2021 Company, Inc.</p>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
      $(document).ready(function () {
        $("#register-form").on("submit", function (event) {
          var password1 = $("#id_password1").val();
          var password2 = $("#id_password2").val();
          var regex = /^(?=.*\d)(?=.*[!#$%&?])(?=.*[a-zA-Z]).{8,}$/;

          if (password1 !== password2) {
            event.preventDefault();
            Swal.fire({
              icon: "error",
              title: "Error",
              text: "Las contraseñas no coinciden. Por favor, intenta nuevamente.",
            });
            return false;
          } else if (!regex.test(password1)) {
            event.preventDefault();
            Swal.fire({
              icon: "error",
              title: "Error",
              text: "La contraseña debe tener al menos 8 caracteres, contener al menos un número, un símbolo (!, #, $, %, & o ?) y una letra.",
            });
            return false;
          }
          return true;
        });
      });
    </script>
    <script>
      document.addEventListener("DOMContentLoaded", function () {
        document.querySelectorAll(".toggle-password").forEach((button) => {
          button.addEventListener("click", function () {
            let input = document.querySelector(
              this.getAttribute("data-target")
            );
            let icon = this.querySelector(".password-icon");

            if (input.type === "password") {
              input.type = "text";
              icon.src =
                "https://cdn-icons-png.flaticon.com/128/8173/8173177.png"; // Ícono de "mostrar"
            } else {
              input.type = "password";
              icon.src =
                "https://cdn-icons-png.flaticon.com/128/158/158746.png"; // Ícono de "ocultar"
            }
          });
        });
      });
    </script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
    {% include 'mensaje.html' %} {% if form.errors %}
    <script>
      document.addEventListener("DOMContentLoaded", function () {
        Swal.fire({
          icon: "error",
          title: "Error en el registro",
          html: "{% for field, errors in form.errors.items %}{% for error in errors %}{{ error }}<br>{% endfor %}{% endfor %}",
        });
      });
    </script>
    {% endif %}
    <script>
      document
        .getElementById("register-form")
        .addEventListener("submit", function (event) {
          event.preventDefault(); // Detiene el envío para depuración
          let formData = new FormData(this);
          for (let pair of formData.entries()) {
            console.log(pair[0] + ": " + pair[1]); // Muestra cada campo en la consola
          }
          this.submit(); // Envía el formulario después de revisar
        });
    </script>
  </body>
</html>